# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-29 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NonMediaItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=150)),
                ('price', models.FloatField()),
                ('weight', models.FloatField()),
                ('length', models.FloatField(blank=True)),
                ('width', models.FloatField(blank=True)),
                ('height', models.FloatField(blank=True)),
                ('item_size', models.CharField(blank=True, max_length=30)),
                ('is_fulfilled', models.BooleanField(default=False)),
                ('item_fulfillment_cost', models.FloatField(blank=True)),
                ('item_category', models.FloatField()),
                ('zero_fulfillment', models.BooleanField(default=False)),
            ],
        ),
    ]
