# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-29 10:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_auto_20160829_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nonmediaitem',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nonmediaitem',
            name='length',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nonmediaitem',
            name='width',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
