# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-29 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_auto_20160829_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='nonmediaitem',
            name='average_order_size',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nonmediaitem',
            name='average_time_stored',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nonmediaitem',
            name='shipping_type',
            field=models.CharField(default='domestic standard', max_length=50),
            preserve_default=False,
        ),
    ]
