# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-29 21:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecommerce', '0006_auto_20160829_1119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nonmediaitem',
            old_name='zero_fulfillment',
            new_name='zero_fulfillment_item',
        ),
        migrations.AddField(
            model_name='nonmediaitem',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='nonmediaitem',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nonmediaitem',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='nonmediaitem',
            name='item_category',
            field=models.CharField(choices=[('3D Printed Products', '3D Printed Products'), ('Amazon Device Accessories', 'Amazon Device Accessories'), ('Amazon Kindle', 'Amazon Kindle'), ('Automotive & Powersports', 'Automotive & Powersports'), ('Baby Products (excluding Baby Apparel)', 'Baby Products (excluding Baby Apparel)'), ('Beauty', 'Beauty'), ('Books', 'Books'), ('Everything Else', 'Everything Else'), ('Cell Phone Devices*', 'Cell Phone Devices*'), ('Clothing & Accessories', 'Clothing & Accessories'), ('Collectible Coins', 'Collectible Coins'), ('Consumer Electronics', 'Consumer Electronics'), ('Electronics Accessories', 'Electronics Accessories'), ('Everything Else', 'Everything Else'), ('Furniture & Decor', 'Furniture & Decor'), ('Health & Personal Care (including Personal Care Appliances)', 'Health & Personal Care (including Personal Care Appliances)'), ('Home & Garden (including Pet Supplies)', 'Home & Garden (including Pet Supplies)'), ('Independent Design', 'Independent Design'), ('Industrial & Scientific (including Food Service and Janitorial & Sanitation)', 'Industrial & Scientific (including Food Service and Janitorial & Sanitation)'), ('Jewelry', 'Jewelry'), ('Kitchen', 'Kitchen'), ('Luggage & Travel Accessories', 'Luggage & Travel Accessories'), ('Major Appliances', 'Major Appliances'), ('Music', 'Music'), ('Musical Instruments', 'Musical Instruments'), ('Office Products', 'Office Products'), ('Outdoors', 'Outdoors'), ('Personal Computers', 'Personal Computers'), ('Shoes, Handbags and Sunglasses', 'Shoes, Handbags and Sunglasses'), ('Software & Computer/Video Games', 'Software & Computer/Video Games'), ('Sports', 'Sports'), ('Sports Collectibles', 'Sports Collectibles'), ('Tools & Home Improvement', 'Tools & Home Improvement'), ('Toys & Games', 'Toys & Games'), ('Video & DVD', 'Video & DVD'), ('Video Games', 'Video Games'), ('Video Game Consoles', 'Video Game Consoles'), ('Watches', 'Watches'), ('Everything Else', 'Everything Else')], max_length=150),
        ),
        migrations.AlterField(
            model_name='nonmediaitem',
            name='item_size',
            field=models.CharField(blank=True, choices=[('small standard', 'small standard'), ('large standard', 'large standard'), ('small oversize', 'small oversize'), ('medium oversize', 'medium oversize'), ('large oversize', 'large oversize'), ('special oversize', 'special oversize')], max_length=30),
        ),
        migrations.AlterField(
            model_name='nonmediaitem',
            name='shipping_type',
            field=models.CharField(choices=[('domestic standard', 'domestic standard'), ('domestic expedited', 'domestic expedited')], max_length=50),
        ),
    ]
