# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-29 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0007_auto_20160829_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='nonmediaitem',
            name='unit_volume',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nonmediaitem',
            name='shipping_type',
            field=models.CharField(choices=[('FBA', 'FBA'), ('domestic standard', 'domestic standard'), ('domestic expedited', 'domestic expedited')], max_length=50),
        ),
    ]
