# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-02 05:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecommerce', '0008_auto_20160829_2148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nonmediaitem',
            name='creator',
        ),
        migrations.AddField(
            model_name='nonmediaitem',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nonmediaitems', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
